// <auto-generated />
using System;
using ECommerce.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7537a3c6-b939-4e6f-9530-43ac571f3749"),
                            Name = "Product 1111",
                            Price = 60.0
                        },
                        new
                        {
                            Id = new Guid("d5401bf6-9671-4456-89f8-10c37df2e514"),
                            Name = "Product 1112",
                            Price = 50.0
                        },
                        new
                        {
                            Id = new Guid("e4453ffc-4836-44d1-b17a-2f31c34292ce"),
                            Name = "Product 1113",
                            Price = 70.0
                        },
                        new
                        {
                            Id = new Guid("6d0d807b-e18e-46b2-b12a-5557b264587a"),
                            Name = "Product 1114",
                            Price = 80.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
